E_vote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from home import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("about_us.urls")),
    path("", include("contact_us.urls")),
    path("", include("home.urls")),
    path("", include("login.urls")),
    path("", include("registration.urls")),
    path("", include("results.urls")),
    path("", include("voter_education.urls")),
    path("", include("polling.urls")),
    path("", TemplateView.as_view(template_name="index.html"), name="home"),
]

home/urls.py
from django.urls import include, path
from . import views

app_name = "home"

urlpatterns = [
    path("home/", views.home, name="home"),
]

polling/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views

app_name = "polling"

urlpatterns = [
    path("polling/", views.polling_page, name="polling_page"),
]

registration/urls.py
from django.urls import path
from . import views

app_name = "registration"

urlpatterns = [
    path("registration/", views.registration, name="registration"),
]

templates/main_head_arelt.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
  </head>

  <body fs-5>
    <marquee
      class="bg-light mt-1"
      onmouseover="this.stop();"
      onmouseout="this.start();"
      direction="left"
      scrollamount="3"
      scrolldelay="30"
      ><strong
        >Note :- we didn't ask your personal details like a bank account details
        or any UPI details or OTP , please do not share such kind of information
        to anyone even our E_Vote office employees !</strong
      ></marquee
    >

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/main_navbar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
  </head>

  <body fs-5>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img
            src="{% static 'logo.png' %}"
            alt="Logo"
            width="40"
            height="34"
            class="d-inline-block align-text-top"
          />
          E voter portal</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item me-2">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'home' %}"
              >
                Home
              </a>
            </li>
            <li class="nav-item me-2">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'registration:registration' %}"
              >
                Registration
              </a>
            </li>
            <li class="nav-item me-2">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'results' %}"
              >
                Results
              </a>
            </li>
            <li class="nav-item me-2">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'about_us' %}"
              >
                About Us
              </a>
            </li>
            <li class="nav-item me-2">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'contact_us' %}"
              >
                Contact Us
              </a>
            </li>
            <li class="nav-item me-2">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'voter_education' %}"
              >
                Voter Education
              </a>
            </li>
          </ul>
          <ul class="navbar-nav me-5 mb-2 mb-lg-0 ustify-content-end">
            <li class="nav-item me-2">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'polling:polling_page' %}"
              >
                Polling
              </a>
            </li>

            <li class="nav-item me-2">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'signup' %}"
              >
                SignUp
              </a>
            </li>

            <li class="nav-item me-2">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'login' %}"
              >
                Login
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>